# Generated by Django 6.0.2 on 2026-03-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='part_name',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
